---
apiVersion: v1
kind: Service
metadata:
  name: ghost
  labels:
    app: ghost
    type: web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 2368
      protocol: TCP
  selector:
    app: ghost
