---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  labels:
    app: ghost
    tier: web
spec:
  selector:
    matchLabels:
      app: ghost
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ghost
        tier: web
    spec:
      containers:
      - name: ghost
        image: ghost:5.23
        env:
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: mysql-service
        - name: database__connection__user
          value: ghost
        - name: database__connection__database
          value: ghost
        - name: database__connection__password
          value: ghost
        ports:
        - containerPort: 2368
      initContainers:
      - name: migrate-ghost
        image: ghost:5.23
        command: ['ghost', 'migrate', '--no-prompt', '--allow-root', '--db', 'mysql', '--dbhost', 'mysql-service', '--dbuser', 'ghost', '--dbpass', 'ghost', '--dbname', 'ghost']
      - name: create-admin-user
        image: mysql
        command: ['mysql', '--host=mysql-service', '--database=ghost', '--password=ghost', '--user=ghost', "--execute=update users set name='ascn', email='ascn@example.com', status='active', password='$2b$10$sCPWMyZr2v3sIavNWzGageBwMfeylrf/WZESS4oEkXQQ4Xow.d2ly0' where id=1;"]
