---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
    tier: database
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - targetPort: 3306
      port: 3306
