---

- name: Undeploy Ghost service
  kubernetes.core.k8s:
    state: absent
    template: ghost/ghost-service.yml
    namespace: default
    wait: true

- name: Undeploy Ghost
  kubernetes.core.k8s:
    state: absent
    template: ghost/ghost-deployment.yml
    namespace: default
    wait: true

- name: Undeploy MySQL service
  kubernetes.core.k8s:
    state: absent
    template: mysql/mysql-service.yml
    namespace: default
    wait: true

- name: Undeploy MySQL
  kubernetes.core.k8s:
    state: absent
    template: mysql/mysql-deployment.yml
    namespace: default
    wait: true

- name: Destroy MySQL data
  kubernetes.core.k8s:
    state: absent
    template: mysql/mysql-pvc.yml
    namespace: default
    wait: true
  when: delete_data is defined and delete_data

- name: Destroy Ghost data
  kubernetes.core.k8s:
    state: absent
    template: ghost/ghost-pvc.yml
    namespace: default
    wait: true
  when: delete_data is defined and delete_data
